name: Build iOS App

on:
  workflow_dispatch: # run manually from GitHub Actions tab
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Podfile with iOS 14 target
        run: |
          mkdir -p ios
          cat > ios/Podfile <<'EOF'
          platform :ios, '14.0'

          use_frameworks!
          use_modular_headers!

          target 'Runner' do
            flutter_application_path = '../'
            eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)
          end
          EOF

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/*.ipa
